import type { ProgramLesson, ProgramModule, QuizQuestion } from "@/lib/program";

export type SurvivalSpec = {
  id: string; order: number; title: string; mystery: string; incident: string;
  evidence: string[]; decision: string; options: string[]; correctIndex: number;
  explanation: string; response: string[]; mission: string; reflection: string; cliffhanger: string;
};

function survivalLesson(spec: SurvivalSpec): ProgramLesson {
  return {
    id: spec.id,
    order: spec.order,
    title: spec.title,
    estimatedMins: 12,
    content: [
      { type: "hook", content: spec.mystery },
      { type: "story", content: `ALERTE DE MISSION — ${spec.incident}` },
      { type: "discovery", content: "Mission Control te demande de ralentir. L'Opposant compte sur une réaction rapide; l'Investigateur cherche d'abord ce qui peut être vérifié." },
      { type: "checklist", content: spec.evidence },
      { type: "reflection", content: spec.decision },
      { type: "tip", content: spec.explanation },
      { type: "checklist", content: spec.response },
      { type: "mission", content: [spec.mission] },
      { type: "reflection", content: spec.reflection },
      { type: "ability", content: `Réflexe débloqué : ${spec.response[0]}` },
      { type: "story", content: spec.cliffhanger },
    ],
    quiz: { question: spec.decision, options: spec.options, correctIndex: spec.correctIndex, explanation: spec.explanation },
  };
}

export const moduleTwoLessonSpecs: SurvivalSpec[] = [
  { id: "bad-guys", order: 1, title: "Who Are the Bad Guys? / Qui sont les attaquants ?", mystery: "Qui attaque réellement les personnes en ligne — et pourquoi ?", incident: "Trois victimes signalent trois incidents différents : un faux paiement, un compte testé avec un outil téléchargé, et une faille signalée sans vol de données.", evidence: ["Un escroc manipule une personne pour obtenir argent ou données.", "Un cybercriminel organise une activité illégale; un fraudeur cherche un bénéfice trompeur.", "Un script kiddie utilise des outils sans toujours les comprendre.", "Un insider abuse d'un accès légitime; un hacker éthique teste avec autorisation pour protéger."], decision: "Qui agit pour protéger un système avec l'autorisation de son propriétaire ?", options: ["Le fraudeur", "Le hacker éthique", "Le scammer", "L'insider malveillant"], correctIndex: 1, explanation: "L'intention, l'autorisation et l'action distinguent les profils. Un hacker éthique travaille dans un cadre permis et communique la faille afin qu'elle soit corrigée.", response: ["Identifier l'objectif et vérifier l'autorisation avant d'étiqueter une personne.", "Conserver les preuves et décrire les faits plutôt que deviner l'identité réelle.", "Signaler l'incident au service ou à une personne responsable."], mission: "Relie trois incidents fictifs au profil le plus probable et justifie chaque choix avec un indice.", reflection: "Quel indice t'empêcherait de confondre un chercheur autorisé avec un criminel ?", cliffhanger: "Tu connais les profils. Prochaine mission : regarder ton propre profil avec les yeux d'un Opposant." },
  { id: "think-like-hacker", order: 2, title: "Think Like a Hacker / Penser comme un attaquant", mystery: "Si quelqu'un voulait t'attaquer, où commencerait-il ?", incident: "Un profil public révèle une école, une date d'anniversaire, un lieu fréquenté, le nom d'un animal et une photo de badge.", evidence: ["La reconnaissance consiste à rassembler des informations avant d'agir.", "Des détails banals deviennent puissants lorsqu'ils sont recoupés.", "Le partage excessif peut aider à deviner des réponses, imiter une personne ou rendre un message crédible.", "Une faiblesse peut être technique, mais l'erreur humaine et la confiance sont souvent plus faciles à exploiter."], decision: "Quel changement réduit le plus immédiatement l'exposition de ce profil ?", options: ["Ajouter plus d'amis", "Masquer les détails personnels et revoir l'audience", "Changer la couleur de la photo", "Publier plus souvent"], correctIndex: 1, explanation: "Réduire les informations publiques et contrôler leur audience enlève des indices utiles à la préparation d'une attaque.", response: ["Réviser les informations publiques et leur audience.", "Retirer les horaires, contacts et lieux trop précis.", "Chercher son nom sans se connecter pour voir ce qu'un inconnu voit."], mission: "Fais un audit privé de ta présence en ligne sans noter de mot de passe ni exposer de donnée dans la plateforme.", reflection: "Quel détail te semblait innocent avant cette enquête ?", cliffhanger: "L'Opposant a ses indices. Il lui reste à provoquer une émotion assez forte pour te faire agir." },
  { id: "social-engineering", order: 3, title: "Social Engineering / Manipulation sociale", mystery: "Pourquoi des personnes intelligentes se font-elles manipuler ?", incident: "Un message prétend venir d'une autorité : « Réponds dans cinq minutes ou ton compte sera fermé. Ne préviens personne. »", evidence: ["L'urgence réduit le temps de réflexion.", "La peur pousse à obéir pour éviter une perte.", "L'autorité empruntée donne une apparence de légitimité.", "La curiosité et la confiance peuvent faire ouvrir un lien ou révéler une information."], decision: "Quel est le premier réflexe devant ce message ?", options: ["Répondre avant cinq minutes", "S'arrêter et vérifier par un canal officiel séparé", "Transférer son code", "Garder le secret"], correctIndex: 1, explanation: "La manipulation perd de sa force lorsque tu interromps l'urgence et vérifies indépendamment l'identité et la demande.", response: ["Stopper l'action et nommer l'émotion provoquée.", "Vérifier par un numéro, une application ou un site officiel trouvé séparément.", "Ne jamais transmettre code, mot de passe ou argent sous pression."], mission: "Analyse trois messages reçus dans la vie réelle en masquant toutes les données personnelles.", reflection: "Quelle émotion te ferait agir le plus vite ?", cliffhanger: "Le prochain message contient un lien presque parfait. Sauras-tu voir ce qu'il cache ?" },
  { id: "phishing", order: 4, title: "Phishing / Hameçonnage", mystery: "Cliquerais-tu sur ce lien ?", incident: "Un SMS annonce un colis bloqué et demande une petite somme sur une page de connexion ressemblant parfaitement au service attendu.", evidence: ["Le phishing peut arriver par email, SMS, appel vocal ou QR code.", "Le nom affiché peut être imité; l'adresse réelle et la destination du lien comptent davantage.", "Une fausse page de connexion vole ce qui y est saisi.", "Une demande inattendue, urgente ou secrète mérite une vérification indépendante."], decision: "Comment vérifier sans ouvrir le lien du message ?", options: ["Répondre au SMS", "Ouvrir soi-même l'application ou le site officiel", "Payer la petite somme", "Transférer le message"], correctIndex: 1, explanation: "Accéder au service par ton propre raccourci ou une adresse officielle évite de faire confiance au chemin fourni par l'attaquant.", response: ["Ne pas cliquer; ouvrir le service officiel séparément.", "Examiner l'expéditeur, la demande et l'adresse réelle.", "Signaler puis supprimer le message après avoir conservé la preuve utile."], mission: "Sauve trois utilisateurs fictifs en expliquant le signal qui doit arrêter chacun.", reflection: "Quel détail vérifieras-tu désormais avant tout clic ?", cliffhanger: "Même sans message, une copie de site peut attendre ta visite." },
  { id: "fake-websites", order: 5, title: "Fake Websites / Faux sites", mystery: "Peux-tu reconnaître un faux site en moins de dix secondes ?", incident: "Deux boutiques utilisent le même logo et les mêmes produits. L'une emploie une adresse légèrement modifiée et exige un paiement immédiat.", evidence: ["Le domaine est la partie centrale de l'adresse appartenant au site; les mots ajoutés autour peuvent tromper.", "HTTPS protège le trajet, mais ne prouve pas que le propriétaire est honnête.", "Une imitation visuelle peut copier logo, couleurs et avis.", "Coordonnées vérifiables, réputation externe et moyens de paiement cohérents apportent du contexte."], decision: "Quel indice est le plus décisif avant de saisir ses données ?", options: ["Le beau logo", "Le domaine exact et sa réputation vérifiable", "La couleur du cadenas", "Le nombre d'images"], correctIndex: 1, explanation: "Le design se copie facilement. Il faut contrôler l'adresse exacte et vérifier l'organisation par une source indépendante.", response: ["Lire le domaine de droite à gauche avant le premier slash.", "Chercher le site officiel par une autre source.", "Quitter la page si elle impose urgence, paiement inhabituel ou données excessives."], mission: "Enquête sur cinq URL fictives et souligne le véritable domaine de chacune.", reflection: "Pourquoi le cadenas ne suffit-il pas à prouver qu'un site est légitime ?", cliffhanger: "Cette fois, le message vient vraiment du compte de ton meilleur ami — mais ton ami ne le contrôle plus." },
  { id: "whatsapp-scams", order: 6, title: "WhatsApp Scams / Arnaques WhatsApp", mystery: "Peut-on t'arnaquer avec le vrai compte de ton meilleur ami ?", incident: "Le compte d'un proche demande en urgence un transfert d'argent, puis réclame un code reçu par SMS pour 'confirmer'.", evidence: ["Un compte compromis conserve le nom, la photo et l'historique qui inspirent confiance.", "Un code de vérification peut permettre de prendre le contrôle d'un compte.", "Une fausse urgence cherche à empêcher l'appel ou la vérification.", "Les faux cadeaux et liens de vote servent souvent à voler un accès ou diffuser l'arnaque."], decision: "Que fais-tu avant toute aide financière ?", options: ["Envoyer rapidement", "Appeler la personne par un autre canal connu", "Partager le code", "Suivre le lien"], correctIndex: 1, explanation: "Un canal séparé permet de vérifier la personne réelle même lorsque son compte habituel est compromis.", response: ["Vérifier la demande hors de la conversation compromise.", "Ne jamais partager un code de connexion ou de vérification.", "Prévenir les contacts, déconnecter les appareils inconnus et lancer la récupération officielle."], mission: "Construis les étapes de récupération d'un compte WhatsApp compromis sans utiliser de données réelles.", reflection: "Quelle question personnelle pourrait confirmer un proche sans révéler une information sensible ?", cliffhanger: "Le prochain piège ne menace pas : il promet une chance exceptionnelle." },
  { id: "fake-opportunities", order: 7, title: "Fake Jobs & Scholarships / Fausses opportunités", mystery: "Reconnaîtrais-tu une fausse offre avant d'envoyer ton CV ?", incident: "Un recruteur promet un emploi immédiat, demande des frais de dossier Mobile Money et réclame pièce d'identité, adresse et coordonnées bancaires.", evidence: ["Une offre sérieuse peut être vérifiée sur le domaine et les canaux officiels de l'organisation.", "Des frais anticipés, une sélection garantie et une urgence inhabituelle sont des alertes.", "Un CV et une pièce d'identité contiennent assez d'informations pour faciliter une usurpation.", "Une adresse gratuite ou proche du vrai domaine doit être confirmée indépendamment."], decision: "Quelle vérification effectuer avant d'envoyer un document ?", options: ["Compter les emojis", "Contacter l'organisation via son site officiel", "Payer pour réserver", "Envoyer d'abord la pièce"], correctIndex: 1, explanation: "La confirmation par un canal officiel indépendant vérifie que l'offre et la personne existent réellement.", response: ["Vérifier l'offre et le recruteur auprès de l'organisation réelle.", "Ne payer aucun frais improvisé pour obtenir une promesse.", "Partager seulement les données nécessaires, au bon moment et au bon destinataire."], mission: "Compare trois candidatures fictives et documente les indices pour ou contre leur légitimité.", reflection: "Quelle donnée de ton CV mérite une protection particulière ?", cliffhanger: "Certaines manipulations ne durent pas cinq minutes : elles construisent la confiance pendant des mois." },
  { id: "romance-investment-scams", order: 8, title: "Romance & Investment Scams / Arnaques affectives et financières", mystery: "Comment une personne peut-elle en manipuler une autre pendant des mois ?", incident: "Une relation en ligne devient très intense, évite toujours les rencontres, puis introduit une plateforme d'investissement aux gains réguliers avant une urgence financière.", evidence: ["La confiance est construite progressivement avant la demande.", "L'isolement et le secret empêchent la victime de recevoir un avis extérieur.", "De faux tableaux de gains peuvent afficher de l'argent impossible à retirer.", "Un premier petit retrait peut servir à convaincre d'investir davantage."], decision: "Quel événement doit interrompre immédiatement le transfert d'argent ?", options: ["Un message gentil", "Une pression secrète et une plateforme invérifiable", "Une photo de profil", "Une longue conversation"], correctIndex: 1, explanation: "La combinaison confiance, secret, pression et argent est un signal majeur. Une relation ne rend pas une opportunité financière vérifiée.", response: ["Suspendre tout paiement et parler à une personne de confiance.", "Vérifier l'identité et la plateforme hors des liens fournis.", "Conserver les preuves, contacter le service financier et signaler rapidement."], mission: "Reconstitue la chronologie d'une arnaque et repère le moment où la confiance devient pression.", reflection: "Pourquoi la honte aide-t-elle l'Opposant à continuer ?", cliffhanger: "Tu sais reconnaître la manipulation. Il faut maintenant fortifier l'appareil qui contient tes accès." },
  { id: "protect-phone", order: 9, title: "Protect Your Phone / Protège ton téléphone", mystery: "Ton téléphone est-il sécurisé maintenant ?", incident: "Un téléphone sans verrouillage fort contient emails, photos, paiements et sessions ouvertes; une application lampe torche demande contacts, micro et localisation.", evidence: ["Les mises à jour corrigent des failles connues.", "Les permissions doivent correspondre à la fonction réelle de l'application.", "Un verrouillage fort limite l'accès après perte ou vol.", "Une sauvegarde permet de récupérer les données sans payer ni céder à une menace."], decision: "Quelle action réduit plusieurs risques dès aujourd'hui ?", options: ["Ignorer les mises à jour", "Mettre à jour, verrouiller et revoir les permissions", "Installer toute application", "Désactiver les sauvegardes"], correctIndex: 1, explanation: "Ces trois contrôles réduisent l'exploitation de failles, l'accès physique et la collecte inutile.", response: ["Activer les mises à jour et un verrouillage fort.", "Supprimer les applications inconnues et limiter les permissions.", "Préparer une sauvegarde et la fonction de localisation à distance."], mission: "Réalise l'audit de ton propre appareil avec un adulte si un réglage t'est inconnu.", reflection: "Quelle application possède une permission dont elle n'a probablement pas besoin ?", cliffhanger: "Le téléphone est fortifié. Mais un seul mot de passe réutilisé peut encore ouvrir toutes les portes." },
  { id: "passwords-mfa", order: 10, title: "Passwords & MFA / Mots de passe et authentification", mystery: "Combien de temps ton mot de passe survivrait-il ?", incident: "Un mot de passe court est réutilisé sur cinq services. Une fuite sur le moins important permet de tester les quatre autres.", evidence: ["Une phrase de passe longue et unique résiste mieux qu'un mot court compliqué mais prévisible.", "Un gestionnaire crée et conserve des mots de passe uniques.", "La MFA ajoute une preuve supplémentaire; un code ne doit jamais être transmis.", "Une passkey utilise la sécurité de l'appareil et résiste mieux aux fausses pages de connexion."], decision: "Quelle combinaison protège le mieux un compte important ?", options: ["Un mot court partout", "Un mot de passe unique avec MFA ou passkey", "Le prénom et l'année", "Un code partagé"], correctIndex: 1, explanation: "L'unicité empêche une fuite de se propager et la seconde preuve bloque de nombreuses prises de compte.", response: ["Utiliser un secret long et unique pour chaque compte.", "Adopter un gestionnaire reconnu ou des passkeys lorsque disponibles.", "Activer la MFA et conserver les codes de récupération en lieu sûr."], mission: "Active la MFA ou une passkey sur un compte, sans jamais saisir ton secret dans cette formation.", reflection: "Quel compte doit être protégé en premier parce qu'il permet de récupérer les autres ?", cliffhanger: "Tes comptes sont mieux protégés. Mais une fausse vidéo peut encore détourner ta confiance." },
  { id: "fake-news-ai", order: 11, title: "Fake News & AI Manipulation / Infox et IA", mystery: "Partagerais-tu cette publication ?", incident: "Une vidéo spectaculaire montre une personnalité annonçant une mesure urgente. Le compte est récent, la source complète manque et d'autres médias ne rapportent rien.", evidence: ["La mésinformation peut être fausse sans intention; la désinformation cherche volontairement à tromper.", "Une image, une voix ou une vidéo peuvent être générées ou modifiées par IA.", "Un contenu réaliste n'est pas une preuve de son origine.", "Source originale, date, contexte et confirmations indépendantes restent essentiels."], decision: "Que faire avant de partager la vidéo ?", options: ["Se fier au réalisme", "Retrouver la source et croiser avec plusieurs sources fiables", "Partager avec un doute", "Compter les vues"], correctIndex: 1, explanation: "La vérification de provenance et le recoupement restent plus fiables que l'apparence ou la popularité.", response: ["Suspendre le partage et retrouver la publication originale.", "Comparer date, contexte et comptes officiels ou médias fiables.", "Signaler le contenu trompeur sans l'amplifier."], mission: "Vérifie trois histoires publiques en documentant source, date, contexte et confirmation.", reflection: "Quel élément d'une vidéo convaincante n'est toujours pas une preuve ?", cliffhanger: "Le prochain incident ne concerne pas seulement une information : une personne est directement blessée." },
  { id: "cyberbullying-harm", order: 12, title: "Cyberbullying & Digital Harm / Harcèlement et préjudices", mystery: "Ton ami t'appelle en pleurant. Que fais-tu d'abord ?", incident: "Des messages humiliants circulent dans un groupe. Une personne menace ensuite de publier une image intime si la victime ne paie pas.", evidence: ["La priorité est la sécurité et le soutien, jamais la curiosité.", "Répondre publiquement ou repartager peut amplifier le préjudice.", "Les preuves utiles conservent compte, date, lien et menace sans diffuser le contenu intime.", "La sextorsion exige l'aide rapide d'un adulte de confiance, de la plateforme et, selon le danger, des autorités."], decision: "Quelle est la première réponse utile à ton ami ?", options: ["Demander l'image", "L'écouter, vérifier sa sécurité et chercher de l'aide", "Payer en secret", "Répondre au groupe"], correctIndex: 1, explanation: "Écouter sans juger et vérifier le danger immédiat permet d'organiser une aide sûre sans aggraver l'exposition.", response: ["Rassurer la victime : elle n'est pas coupable et ne doit pas rester seule.", "Ne pas payer, négocier seul ou repartager; conserver les preuves avec prudence.", "Bloquer, signaler et impliquer rapidement un adulte ou service compétent."], mission: "Construis un plan de réponse indiquant qui appeler, quoi conserver et quoi ne jamais diffuser.", reflection: "Quelle phrase aiderait une victime à parler sans honte ?", cliffhanger: "Tu sais soutenir une victime. Dernière compétence avant le cas final : reprendre le contrôle après un incident." },
  { id: "incident-response", order: 13, title: "When Things Go Wrong / Quand ça tourne mal", mystery: "Tu te réveilles : ton compte a disparu. Quel est ton premier geste ?", incident: "Le mot de passe a changé, des messages partent à tes contacts et ton téléphone affiche une application inconnue.", evidence: ["Il faut d'abord contenir l'incident depuis un appareil sûr.", "L'email principal et le numéro de récupération contrôlent souvent les autres comptes.", "Les sessions inconnues, règles de transfert et applications connectées peuvent maintenir l'accès de l'attaquant.", "Prévenir les contacts limite les dégâts; conserver les preuves aide le support et le signalement."], decision: "Quelle séquence est la plus sûre ?", options: ["Paniquer et tout supprimer", "Sécuriser l'email, récupérer le compte, fermer les sessions, prévenir", "Payer l'attaquant", "Créer seulement un nouveau profil"], correctIndex: 1, explanation: "La récupération efficace commence par le point de contrôle principal, coupe les accès persistants puis limite les conséquences.", response: ["Utiliser un appareil sûr et sécuriser d'abord l'email principal.", "Suivre la récupération officielle, changer les secrets et fermer les sessions inconnues.", "Vérifier l'appareil, prévenir les contacts, conserver les preuves et signaler."], mission: "Crée un plan personnel avec liens officiels de récupération et personnes de confiance, sans y écrire tes mots de passe.", reflection: "Si ton téléphone disparaissait aujourd'hui, saurais-tu récupérer ton email ?", cliffhanger: "Mission Control se tait. Le dernier dossier ne contient que des preuves : à toi de mener toute l'enquête." },
  { id: "final-case", order: 14, title: "The Final Case / L'affaire finale", mystery: "Peux-tu protéger une victime sans aucune instruction ?", incident: "Une étudiante répond à une fausse bourse, réutilise son mot de passe, partage un code sous pression, puis son compte demande de l'argent à ses proches et diffuse une fausse vidéo.", evidence: ["Preuve A : domaine proche mais différent de l'organisation officielle.", "Preuve B : frais urgents et demande de pièce d'identité.", "Preuve C : alerte de connexion, code transmis et sessions inconnues.", "Preuve D : messages financiers envoyés aux contacts et contenu manipulé."], decision: "Quelle action doit lancer ton plan ?", options: ["Partager l'histoire", "Mettre la victime en sécurité et contenir les accès depuis un appareil sûr", "Contacter l'Opposant", "Effacer toutes les preuves"], correctIndex: 1, explanation: "La sécurité de la personne et le confinement de l'incident passent avant l'enquête publique ou la confrontation.", response: ["Identifier phishing, manipulation, réutilisation et prise de compte à partir des preuves.", "Sécuriser l'email, récupérer les comptes, fermer les sessions et prévenir les contacts.", "Documenter sans exposer la victime, signaler et expliquer comment chaque indice a conduit à l'action."], mission: "Rédige ton rapport final : menace, indices, protection immédiate, récupération et prévention.", reflection: "Quel réflexe du module a le plus changé ta manière de réagir ?", cliffhanger: "Dossier clos. Tu ne termines pas avec la peur : tu termines avec un plan. Tu sais quoi faire maintenant." },
];

const moduleQuiz: QuizQuestion[] = moduleTwoLessonSpecs.slice(0, 10).map((spec, index) => ({
  id: `m2-final-${spec.id}`,
  question: spec.decision,
  options: spec.options,
  correctIndex: spec.correctIndex,
  explanation: spec.explanation,
  points: index === 9 ? 20 : 10,
}));

export const moduleTwo: ProgramModule = {
  id: "digital-survivor", week: 2,
  title: "Digital Survivor / Survivant du Numérique",
  subtitle: "Reconnaître le danger, se protéger et aider quelqu'un d'autre",
  summary: "Un entraînement de survie numérique fondé sur des incidents réalistes, des décisions et des missions pratiques.",
  color: "#B5123F", icon: "shield",
  outcomes: ["Reconnaître la manipulation", "Protéger appareils et comptes", "Réagir à un incident", "Aider sans aggraver le danger"],
  status: "ready", progressPercent: 0,
  lessons: moduleTwoLessonSpecs.map(survivalLesson),
  quiz: moduleQuiz,
};
